services:
  ethereum_scanner:
    container_name: ethereum_scanner
    image: thinhhv/ethereum-scanner:latest
    restart: always
#    pull_policy: always
    network_mode: bridge
    volumes:
      - ./config/local.yaml:/app/config/production.yaml
      # Uncomment if enable log to file
      # - ./logs:/app/logs
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
