services:
  ethereum_scanner:
    container_name: ethereum_scanner
    image: thinhhv/ethereum-scanner:latest
    restart: always
    build: .
    network_mode: bridge
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
